<?php

namespace Database\Seeders;

use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TagSeeder extends Seeder
{
    public function run(): void
    {
        $tags = [
            'AWS',
            'AWS Architecture',
            'AWS Auto Scaling',
            'AWS Best Practices',
            'AWS CDK',
            'AWS CloudWatch',
            'AWS Development',
            'AWS Hosting',
            'AWS Infrastructure',
            'AWS Migration',
            'AWS Migration Best Practices',
            'AWS Monitoring',
            'AWS Networking',
            'AWS Redshift',
            'AWS Services',
            'AWS System Manager',
            'AWS to Azure Migration',
            'AWS Updates',
            'Azure',
            'Azure Cloud Migration',
            'Azure Migration Best Practices',
            'Backup Solutions',
            'Benefits of DevOps',
            'Business Efficiency',
            'Business Expenses',
            'CI/CD',
            'CLI Installation',
            'Cloud Architecture',
            'Cloud Based Security',
            'Cloud Computing',
            'Cloud Computing Benefits',
            'Cloud Computing Best Practices',
            'Cloud Cost Optimization',
            'Cloud Expense Management',
            'Cloud Hosting',
            'Cloud Infrastructure',
            'Cloud Metrics',
            'Cloud Migration',
            'Cloud Migration Best Practices',
            'Cloud Monitoring',
            'Cloud Native',
            'Cloud Security',
            'Cloud Services',
            'Cloud Services for Small Businesses',
            'Cloud Storage',
            'Cloud Storage Solutions',
            'Continuous Deployment',
            'Continuous Integration',
            'Continuous Integration and Continuous Delivery (CI/CD)',
            'Cost Allocation',
            'Cost Optimization',
            'Custom Metrics',
            'Cybersecurity',
            'Cyber Threats',
            'Data Analytics',
            'Data Archiving',
            'Data Backup Solutions',
            'Data Insertion',
            'Data Management',
            'Data Protection',
            'Data Security',
            'Data Storage',
            'Data Transfer',
            'Database Management',
            'Database Migration',
            'Database Optimization',
            'DevOps',
            'DevOps Practices',
            'DevOps vs Agile',
            'Digital Transformation',
            'Directory Services',
            'DynamoDB',
            'Effective Cloud Spending',
            'Finance',
            'Financial Management',
            'Function as a Service',
            'GitLab Management',
            'Google Cloud Platform',
            'Group Policy',
            'High-Performance File Systems',
            'IaaS',
            'Infrastructure as Code',
            'Infrastructure Architecture',
            'Infrastructure Management',
            'Infrastructure Optimization',
            'Innovation in Technology',
            'Investment Strategies',
            'IT Infrastructure',
            'LDAP',
            'LDAP Management',
            'Long-Term Data Retention',
            'Managed IT Services',
            'Managed Security Services',
            'Managed Services',
            'Microservices',
            'Monitoring Solutions',
            'Multi Cloud',
            'Network Security',
            'NoSQL Databases',
            'Operations',
            'Optimizing Cloud Budget',
            'OU Groups',
            'Outsourcing',
            'Public Cloud',
            'RabbitMQ',
            'Scalability',
            'Scalable and Resilient Applications',
            'Security & Compliance',
            'Serverless Computing',
            'Serverless Monitoring',
            'Software Development',
            'Tech Events',
            'Technology',
            'Technology Trends',
            'Terraform',
            'Trunk-Based Development',
            'User Authentication',
            'User Management',
            'Virtual Private Network',
            'Virtualization',
            'Website Development',
            'Well-Architected Framework',
        ];
        foreach ($tags as $tag) {
            Tag::insert([
                'name' => $tag,
                'slug' => Str::slug($tag),
                'created_at' => Carbon::now(),
            ]);
        }

    }
}
