name: site-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 8586-dev-relationships

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  site-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add SSH key to known hosts
        run: ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Conditionally backup public/storage directory
        run: ssh ubuntu@${{ secrets.HOST }} 'if [ -d "/var/www/laravel_blog/storage/app/public" ]; then mkdir -p ~/backup_uploads && sudo mv /var/www/laravel_blog/storage/app/public ~/backup_uploads/; fi'

      - name: Delete Existing directory if present
        run: ssh ubuntu@${{ secrets.HOST }} 'if [ -d "/var/www/laravel_blog/" ]; then sudo rm -rf /var/www/laravel_blog ; else echo "Directory does not exist."; fi'
        shell: bash

      - name: Create directory and change ownership
        run: ssh ubuntu@${{ secrets.HOST }} 'sudo mkdir -p /var/www/laravel_blog && sudo chown -R ubuntu:www-data /var/www/laravel_blog && sudo chmod -R 775 /var/www/laravel_blog'
        shell: bash

      - name: Create .env file
        run: |
          echo "APP_NAME=laravel_blog" >> .env
          echo "APP_ENV=local" >> .env
          echo "APP_KEY=base64:/" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env

          echo "LOG_CHANNEL=stack" >> .env
          echo "LOG_DEPRECATIONS_CHANNEL=null" >> .env
          echo "LOG_LEVEL=debug" >> .env

          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel_blog" >> .env
          echo "DB_USERNAME=ugra" >> .env
          echo "DB_PASSWORD=ugra1234" >> .env
        shell: bash

      - name: Sync project files
        run: |
          rsync -avh --rsync-path="sudo rsync" --exclude='.git/' ./ ubuntu@${{ secrets.HOST }}:/var/www/laravel_blog/
        shell: bash

      - name: Restore public/storage directory if backup exists
        run: ssh ubuntu@${{ secrets.HOST }} 'if [ -d "~/backup_uploads" ]; then sudo mv ~/backup_uploads/* /var/www/laravel_blog/storage/app/public/; fi && sudo rm -rf ~/backup_uploads'

      - name: Ensure storage directories exist
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /var/www/laravel_blog/storage && mkdir -p framework/sessions framework/views framework/cache/data logs'

      - name: Set Directory Permissions for Storage
        run: |
          ssh ubuntu@${{ secrets.HOST }} 'sudo chmod -R 775 /var/www/laravel_blog/storage'
          ssh ubuntu@${{ secrets.HOST }} 'sudo chown -R www-data:www-data /var/www/laravel_blog/storage'

      - name: Set Directory Permissions for Public Directory
        run: |
          ssh ubuntu@${{ secrets.HOST }} 'sudo chown -R www-data:www-data /var/www/laravel_blog/public/'
          ssh ubuntu@${{ secrets.HOST }} 'sudo chmod -R 775 /var/www/laravel_blog/public/'

      - name: Set Laravel log file permissions
        run: |
          ssh ubuntu@${{ secrets.HOST }} 'sudo touch /var/www/laravel_blog/storage/logs/laravel.log'
          ssh ubuntu@${{ secrets.HOST }} 'sudo chown www-data:www-data /var/www/laravel_blog/storage/logs/laravel.log'
          ssh ubuntu@${{ secrets.HOST }} 'sudo chmod 664 /var/www/laravel_blog/storage/logs/laravel.log'
        shell: bash

      - name: Set Laravel storage permissions
        run: |
          ssh ubuntu@${{ secrets.HOST }} 'sudo chown -R www-data:www-data /var/www/laravel_blog/storage'
          ssh ubuntu@${{ secrets.HOST }} 'sudo chmod -R 775 /var/www/laravel_blog/storage'

      - name: Create vendor directory with correct permissions
        run: ssh ubuntu@${{ secrets.HOST }} 'sudo mkdir -p /var/www/laravel_blog/vendor && sudo chown -R ubuntu:www-data /var/www/laravel_blog/vendor && sudo chmod -R 775 /var/www/laravel_blog/vendor'

      - name: Install Dependencies
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /var/www/laravel_blog/ && composer install --no-dev'

      - name: Generate Application Key
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /var/www/laravel_blog/ && php artisan key:generate'

      - name: Cache Configuration
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /var/www/laravel_blog/ && php artisan config:cache && php artisan route:cache'

      - name: Run Migrations
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /var/www/laravel_blog/ && php artisan migrate --no-interaction --force'

      - name: Set Laravel bootstrap/cache permissions
        run: |
          ssh ubuntu@${{ secrets.HOST }} 'sudo chown -R www-data:www-data /var/www/laravel_blog/bootstrap/cache'
          ssh ubuntu@${{ secrets.HOST }} 'sudo chmod -R 775 /var/www/laravel_blog/bootstrap/cache'
