# sudo rm -rf * && sudo rm -rf .*
name: site-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 8586-dev-relationships

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  site-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add SSH key to known hosts
        run: ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # - name: Conditionally backup public/uploads directory
      #   run: ssh ubuntu@${{ secrets.HOST }} 'if [ -d "/home/ubuntu/laravel_blog/public/uploads" ]; then mkdir -p ~/backup_uploads && mv /home/ubuntu/laravel_blog/public/uploads/* ~/backup_uploads/; fi'

      - name: Delete Existing Assets
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /home/ubuntu/laravel_blog/ && sudo rm -rf .* && sudo rm -rf *'

      - name: Create .env file
        run: |
          echo "APP_NAME=DevOpsConsoles" >> .env
          echo "APP_ENV=local" >> .env
          echo "APP_KEY=base64:/" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=https://devopsconsoles.com" >> .env

          echo "LOG_CHANNEL=stack" >> .env
          echo "LOG_DEPRECATIONS_CHANNEL=null" >> .env
          echo "LOG_LEVEL=debug" >> .env

          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel_blog" >> .env
          echo "DB_USERNAME=ugra" >> .env
          echo "DB_PASSWORD=ugra1234" >> .env

          echo "BROADCAST_DRIVER=log" >> .env
          echo "CACHE_DRIVER=file" >> .env
          echo "FILESYSTEM_DISK=local" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "SESSION_DRIVER=file" >> .env
          echo "SESSION_LIFETIME=120" >> .env
        shell: bash

      - name: Sync project files
        run: |
          rsync -avh --exclude='/storage/*' --exclude='/vendor/*' --exclude='.git/' -e "ssh" ./ ubuntu@${{ secrets.HOST }}:/home/ubuntu/laravel_blog/ --rsync-path="sudo rsync"
        shell: bash

      # - name: Move files if present and remove directory
      #   run: |
      #     ssh ubuntu@${{ secrets.HOST }} 'if [ -d "~/backup_uploads" ]; then mv ~/backup_uploads/* /home/ubuntu/laravel_blog/public/uploads/; fi; rm -rf ~/backup_uploads/'

      - name: Ensure storage directories exist
        run: |
          ssh ubuntu@${{ secrets.HOST }} 'cd /home/ubuntu/laravel_blog/storage && sudo mkdir -p framework framework/sessions framework/views framework/cache/data logs'
          ssh ubuntu@${{ secrets.HOST }} 'sudo chown ubuntu:ubuntu -R /home/ubuntu/laravel_blog/storage'
          ssh ubuntu@${{ secrets.HOST }} 'sudo chmod -R 775 /home/ubuntu/laravel_blog/storage'

      - name: Set Laravel log file permissions
        run: |
          ssh ubuntu@${{ secrets.HOST }} 'touch /home/ubuntu/laravel_blog/storage/logs/laravel.log'

      - name: Install Dependencies
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /home/ubuntu/laravel_blog/ && composer install --no-dev'

      - name: Generate Application Key
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /home/ubuntu/laravel_blog/ && php artisan key:generate'

      - name: Cache Configuration
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /home/ubuntu/laravel_blog/ && php artisan config:cache && php artisan route:cache'

      - name: Run Migrations
        run: ssh ubuntu@${{ secrets.HOST }} 'cd /home/ubuntu/laravel_blog/ && php artisan migrate --no-interaction --force'

#       - name: Set Laravel folder permission
#         run: |
#           ssh ubuntu@${{ secrets.HOST }} 'sudo chown www-data:www-data -R /home/ubuntu/laravel_blog/'
#           ssh ubuntu@${{ secrets.HOST }} 'sudo chmod -R 775 /home/ubuntu/laravel_blog/'
# #
